Roberto:

    # Publish all joint states
    joints_update:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
#    JointA_EffortController:                                               # Name of the controller
#      type: effort_controllers/JointPositionController         # Since JointA uses effort interface this controller type is  used      
#      joint: JointA                                                                # Name of the joint for which this controller belongs to.
#      pid: {p: 100.0, i: 10.0, d: 1.0}                                    # PID values
#    
#    JointB_EffortController:                                             
#      type: effort_controllers/JointPositionController        # Since JointB uses effort interface this controller type is  used   
#      joint: JointB                                                                 
#      pid: {p: 1.0, i: 1.0, d: 0.0}
#
#    JointC_PositionController:
#      type: position_controllers/JointPositionController    # Since JointC uses position interface this controller type is  used 
#      joint: JointC
#
#    JointD_VelocityController:
#      type: velocity_controllers/JointVelocityController
#      joint: JointD
#
#    JointE_VelocityController:
#      type: velocity_controllers/JointVelocityController
#      joint: JointE
#
    JointR_EffortController:
      type: effort_controllers/JointVelocityController
      joint: JointR
      pid: {p: 0.00003, i: 0.00007, d: 0, i_clamp_min: -150, i_clamp_max: 150, antiwindup: True }

    JointL_EffortController:
      type: effort_controllers/JointVelocityController
      joint: JointL
      pid: {p: 0.00003, i: 0.00007, d: 0, i_clamp_min: -150, i_clamp_max: 150, antiwindup: True }
