joint_limits:
    right_wheel_joint:
      has_position_limits: false
      min_position: 0
      max_position: 0
      has_velocity_limits: true
      max_velocity: 2.62
      min_velocity: -2.62
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    
    left_wheel_joint:
      has_position_limits: false
      min_position: 0
      max_position: 0
      has_velocity_limits: true
      max_velocity: 2.62
      min_velocity: -2.62
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0

#    JointR:
#      has_position_limits: false
#      min_position: 0
#      max_position: 3.14
#      has_velocity_limits: true
#      max_velocity: 1000000
#      has_acceleration_limits: false
#      max_acceleration: 0.0
#      has_jerk_limits: false
#      max_jerk: 0
#      has_effort_limits: true
#      max_effort: 1
#      min_effort: -1
#
#    JointL:
#      has_position_limits: false
#      min_position: 0
#      max_position: 3.14
#      has_velocity_limits: true
#      max_velocity: 1000000
#      has_acceleration_limits: false
#      max_acceleration: 0.0
#      has_jerk_limits: false
#      max_jerk: 0
#      has_effort_limits: true
#      max_effort: 1
#      min_effort: -1

#    JointA:
#      has_position_limits: true
#      min_position: -1.57
#      max_position: 1.57
#      has_velocity_limits: true
#      max_velocity: 1.5
#      has_acceleration_limits: false
#      max_acceleration: 0.0
#      has_jerk_limits: false
#      max_jerk: 0
#      has_effort_limits: true
#      max_effort: 255
#
#    JointB:
#      has_position_limits: true
#      min_position: 0
#      max_position: 3.14
#      has_velocity_limits: true
#      max_velocity: 1.5
#      has_acceleration_limits: false
#      max_acceleration: 0.0
#      has_jerk_limits: false
#      max_jerk: 0
#      has_effort_limits: true
#      max_effort: 255
#      
#    JointC:
#      has_position_limits: true
#      min_position: 0
#      max_position: 3.14
#      has_velocity_limits: false
#      max_velocity: 0
#      has_acceleration_limits: false
#      max_acceleration: 0.0
#      has_jerk_limits: false
#      max_jerk: 0
#      has_effort_limits: false
#      max_effort: 0
#
#    JointD:
#      has_position_limits: false
#
#    JointE:
#      has_position_limits: false
#
